---
title: "Re do thesis graphs"
author: "Sam Rozal"
date: "12/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(ggbeeswarm)
library(lubridate)
library(janitor)
```

```{r}
quadrats_20 <- read_csv(here("data", "quadrats_through_2020.csv"),na=c("", " ", "  "))
```

```{r}
quadrats_clean <- clean_names(quadrats_20) 
quadrats_clean$date[78] <-"8/10/2019" 
quadrats_clean$date[122] <- "11/10/2019"

quadrats_date <- quadrats_clean %>% 
  mutate(date_new = mdy(date))
```

  
```{r}
ggplot(data=quadrats_date, aes(x=month, y=accumlation_items_m2))+
  geom_beeswarm(aes(color=beach))+
  geom_boxplot(fill=NA, width= 0.4, outlier.color="red")
```

```{r}
debris_summary_season <- quadrats_date %>% 
  group_by(season) %>% 
  summarize(count=n(),
           median=median(accumlation_items_m2),
           mean=mean(accumlation_items_m2))

debris_summary_season
```

```{r}
debris_summary_beach <- quadrats_date %>% 
  group_by(beach) %>% 
  summarize(count=n(),
           median=median(accumlation_items_m2),
           mean=mean(accumlation_items_m2))

debris_summary_beach 
```

```{r}
ggplot(data=debris_summary_season, aes(x=season, y=mean))+
  geom_col()
```
```{r}
ggplot(data=debris_summary_beach, aes(x=beach, y=mean))+
  geom_col()
```
